/**
 * Type Definitions for Search Pipeline
 * 
 * This file defines the core data structures used throughout the search pipeline.
 * All pipeline functions ultimately produce or consume the 'candidate' type.
 * 
 * CONNECTIONS:
 * - Used by: webPipeline.ts, directPipeline.ts, searchChain.ts, finalValidate.ts
 * - Represents the final output shape returned to the frontend
 * 
 * IMPACT:
 * - Changing this type will affect all pipeline components
 * - The frontend expects this exact structure in API responses
 */

// Candidate type represents the final answer structure returned by all search modes
// This is the unified output type that both web and direct pipelines produce
export type candidate = {
  // The final answer text generated by the LLM
  answer: string;
  // Array of source URLs used to generate the answer (empty for direct mode)
  sources: string[];
  // Indicates which pipeline was used: "web" (with browsing) or "direct" (LLM only)
  mode: "web" | "direct";
};

// Notes on routing logic:
// - Queries longer than 70 characters -> web mode (browse and summarize)
// - Queries matching specific patterns (comparisons, prices, news, etc.) -> web mode
// - Short, simple queries -> direct mode (LLM only, no browsing)
